image: node:18 

services:
  - mongo:latest

variables:
  METEOR_ALLOW_SUPERUSER: 1
  GIT_SSL_NO_VERIFY: 'true'

before_script:
  - npm install
  - apt-get update && apt-get install -y mongodb
  - mkdir dbpath
  - mongod --dbpath dbpath

stages:
  - code standard
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.Typescript checker:
  stage: code standard
  script:
    - npm run typecheck

.Lint:
  stage: code standard
  script:
    - npm run lint

.Spell checker:
  stage: code standard
  script:
    - npm run cspell

Unit testing:
  stage: test
  script:
    - npm run test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: .coverage/coverage.txt
