image: node:latest 

# services:
#   - mongo:latest

cache:
  paths:
    - node_modules/

variables:
  GIT_SSL_NO_VERIFY: 'true'
  MONGODB_VERSION: 5.0.0

before_script:
  - npm install
  - apt-get update && sudo apt-get install gnupg curl
  - curl -fsSL https://www.mongodb.org/static/pgp/server-5.0.asc | \ sudo gpg -o /usr/share/keyrings/mongodb-server-5.0.gpg \ --dearmor
  - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-5.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  - sudo apt-get update
  - apt-get update && apt-get install -y mongodb-org
  - mongod --fork --logpath /var/log/mongodb.log
  - sleep 5

stages:
  - code standard
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.Typescript checker:
  stage: code standard
  script:
    - npm run typecheck

.Lint:
  stage: code standard
  script:
    - npm run lint

.Spell checker:
  stage: code standard
  script:
    - npm run cspell

Unit testing:
  stage: test
  script:
    - npm run test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: .coverage/coverage.txt

after_script:
  - mongo admin --eval "db.shutdownServer()"